namespace My.D3.Application.PublicService.AppServices.Grid
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    /// <summary>
    /// 数据接口
    /// </summary>
    public class DataGridAppService
    {

        ///// <summary>
        ///// 获取Gird的数据
        ///// </summary>
        ///// <param name="inDto">表格接收参数</param>
        ///// <returns>grid</returns>
        //private Task<string> GetGridList(GetGridListInDto inDto);

    }
}
